"use client";

import { useState } from "react";
import styles from "./SendPanel.module.css";

interface SendPanelProps {
  result: string;
  resultLabel: string;
  workflowName: string;
  practiceName?: string;
  isPatientFacing: boolean;
}

export default function SendPanel({
  result, resultLabel, workflowName,
  practiceName = "",
  isPatientFacing,
}: SendPanelProps) {
  const [to, setTo] = useState("");
  const [sending, setSending] = useState(false);
  const [sent, setSent] = useState(false);
  const [comingSoon, setComingSoon] = useState(false);
  const [error, setError] = useState("");

  const handleSend = async () => {
    if (!to || !to.includes("@")) { setError("Enter a valid email address."); return; }
    if (!result) { setError("No content to send."); return; }
    setError(""); setSending(true); setComingSoon(false); setSent(false);

    const html = `
      <div style="font-family: Georgia, serif; max-width: 640px; margin: 0 auto; color: #0a1628;">
        <div style="background: #0a1628; padding: 24px 32px; margin-bottom: 32px;">
          <span style="color: #fff; font-size: 20px; font-style: italic;">${practiceName || "FlowMD"}</span>
        </div>
        <div style="padding: 0 32px;">
          <h2 style="font-size: 13px; letter-spacing: 0.15em; text-transform: uppercase; color: #c41230; margin-bottom: 24px;">${resultLabel}</h2>
          <div style="font-size: 15px; line-height: 1.85; white-space: pre-wrap;">${result.replace(/\n/g, "<br/>")}</div>
        </div>
        <div style="padding: 24px 32px; margin-top: 32px; border-top: 1px solid #e8d0d4; font-size: 11px; color: #6b7d99; line-height: 1.6;">
          This document was generated by FlowMD and is intended for informational purposes only. It is not a bill or legal notice. Please review with qualified billing staff before acting on this information.
        </div>
      </div>
    `;

    try {
      const res = await fetch("/api/send-email", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ to, subject: `${resultLabel} — ${practiceName || "FlowMD"}`, html, practiceName }),
      });
      const data = await res.json();
      if (data.comingSoon) {
        setComingSoon(true);
      } else if (data.error) {
        setError(data.error);
      } else {
        setSent(true);
        setTo("");
      }
    } catch {
      setError("Something went wrong.");
    } finally {
      setSending(false);
    }
  };

  const handleDownloadPDF = () => {
    const printContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <title>${resultLabel}</title>
        <style>
          body { font-family: Georgia, serif; max-width: 680px; margin: 40px auto; color: #0a1628; font-size: 14px; line-height: 1.85; }
          .header { border-bottom: 2px solid #0a1628; padding-bottom: 16px; margin-bottom: 32px; display: flex; justify-content: space-between; align-items: baseline; }
          .logo { font-size: 22px; font-style: italic; }
          .date { font-size: 13px; color: #6b7d99; }
          .label { font-size: 10px; letter-spacing: 0.15em; text-transform: uppercase; color: #c41230; margin-bottom: 20px; }
          .content { white-space: pre-wrap; }
          .footer { margin-top: 48px; padding-top: 16px; border-top: 1px solid #e8d0d4; font-size: 10px; color: #6b7d99; line-height: 1.6; }
          @media print { body { margin: 0; } }
        </style>
      </head>
      <body>
        <div class="header">
          <span class="logo">${practiceName || "FlowMD"}</span>
          <span class="date">${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}</span>
        </div>
        <div class="label">${resultLabel}</div>
        <div class="content">${result}</div>
        <div class="footer">This document was generated by FlowMD and is for informational purposes only. It is not a bill or legal notice. Review with qualified billing staff before use.</div>
      </body>
      </html>
    `;

    const win = window.open("", "_blank");
    if (!win) return;
    win.document.write(printContent);
    win.document.close();
    win.focus();
    setTimeout(() => { win.print(); }, 500);
  };

  if (!result) return null;

  return (
    <div className={styles.sendPanel}>
      <button className={styles.pdfBtn} onClick={handleDownloadPDF}>
        ↓ Download PDF
      </button>

      <div className={styles.emailRow}>
        <input
          className={styles.emailInput}
          type="email"
          placeholder={isPatientFacing ? "Patient email address" : "Recipient email address"}
          value={to}
          onChange={e => { setTo(e.target.value); setSent(false); setComingSoon(false); setError(""); }}
          autoComplete="off"
        />
        <button
          className={`${styles.sendBtn} ${comingSoon ? styles.sendBtnSoon : ""} ${sent ? styles.sendBtnSent : ""}`}
          onClick={handleSend}
          disabled={sending}
        >
          {sending ? "Sending…" : sent ? "✓ Sent" : "Send"}
        </button>
      </div>

      {error && <div className={styles.errorMsg}>{error}</div>}

      {comingSoon && (
        <div className={styles.comingSoonMsg}>Email delivery coming soon.</div>
      )}
    </div>
  );
}
